### ISSUE TITLE
Crash when putting in the mod

### ISSUE THREAD

**Issue by Exdead12** [tr7zw/FirstPersonModel-Fabric#46]
I have some problems with the mod, when i put it in the folder "mod" and then i start minecraft with fabric it crashes.
i have installed Fabric for minecraft 1.16.4. same for the mod, anyway does anyone know how to fix this? 
Here is the crash log:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 15/11/20 9.47
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect(Lnet/minecraft/class_315;)I in firstperson.mixins.json:FishingBobberRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap FirstPersonMod-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.<init>(class_310.java:527)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 852745104 bytes (813 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.5.6
		fabric: Fabric API 0.25.7+1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+ec7e203b3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f3a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
		fabricloader: Fabric Loader 0.10.7
		firstperson: FirstpersonModel 1.2.2
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.9+build.13
	Launched Version: fabric-loader-0.10.7-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.09, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor

**Comment by tr7zw** [comment]
I was about to sugest that you check that everything is the newest version, but it appears you use "firstperson: FirstpersonModel 1.2.2". The latest release working with 1.16.4 is 1.3.0 https://www.curseforge.com/minecraft/mc-mods/first-person-model/files/3034039. 1.2.2 was for 1.16.0/1.16.1.
